version: '2'

services:

  prometheus:
    restart: "always"
    tty: true
    stdin_open: true
    command:
    - -config.file=/etc/prometheus/prometheus.yml
    - -alertmanager.url=http://alertmanager:9093
    - -storage.local.path=/prometheus
    - -web.console.libraries=/etc/prometheus/console_libraries
    - -web.console.templates=/etc/prometheus/consoles
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alertrules.conf:/etc/prometheus/alertrules.conf
    image: prom/prometheus:v1.4.0
    ports:
      - 9090:9090

  alertmanager:
    command:
      - -config.file=/alertmanager.conf
    stdin_open: true
    tty: true
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager.conf:/alertmanager.conf
    ports:
      - 9093:9093/tcp

  grafana:
    restart: "always"
    tty: true
    stdin_open: true
    image: grafana/grafana:3.1.0
    ports:
      - 3000:3000

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"

  cadvisor:
    image: google/cadvisor:latest
    restart: "always"
    tty: true
    stdin_open: true
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    ports:
      - "8080:8080"
