version: '2'

services:

  prometheus:
    restart: "always"
    tty: true
    stdin_open: true
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    image: prom/prometheus:v1.0.1
    ports:
      - 9090:9090

  grafana:
    restart: "always"
    tty: true
    stdin_open: true
    image: grafana/grafana:3.1.0
    ports:
      - 3000:3000

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"

  cadvisor:
    image: google/cadvisor:latest
    restart: "always"
    tty: true
    stdin_open: true
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    ports:
      - "8080:8080"
