version: '2'

services:

  prometheus:
    volumes:
      - /etc/prometheus/
    image: prom/prometheus:latest
    ports:
    - "9090:9090"

  grafana:
    image: grafana/grafana:3.1.0
    ports:
    - "3000:3000"

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    network_mode: "host"
