global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: prometheus-metrics

scrape_configs:

- job_name: HostMetrics-Appservers
  scrape_interval: 15s
  static_configs:
    - targets:
      - 'node-exporter:9100'

- job_name: ContainerMetrics
  scrape_interval: 15s
  static_configs:
    - targets:
      - 'cadvisor:8080'
