global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: prometheus-metrics

scrape_configs:

- job_name: HostMetrics
  scrape_interval: 15s
  static_configs:
    - targets:
      - 'node-exporter:9100'

- job_name: ContainerMetrics
  scrape_interval: 15s
  static_configs:
    - targets:
      - 'cadvisor:8080'

- job_name: 'federate'
  scrape_interval: 15s
  honor_labels: true
  metrics_path: '/federate'
  scheme: https
  params:
    'match[]':
      - '{job="node"}'
      - '{__name__=~"^up:"}'
      - '{__name__=~"^nodeload:"}'

  static_configs:
    - targets:
      - 'prometheus.wmflabs.org:443'

rule_files:
  - /etc/prometheus/alertrules.conf
